name: 04 Using Actions
on: workflow_dispatch
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: 04-using-actions/react-app
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '22.17.0'
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm test