name: 05 - 2 - Filters Activity Types
on:
    pull_request:
        types: [closed]
        branches: [main]

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Echo PR
              run: echo "Whenever a PR  is closed and base branch is main"